-- =============================================================================
-- Maintenance records (resolves R-7)
-- =============================================================================
-- Adds MaintenanceRecord with its two enums, the MAINTENANCE numbering scope
-- (MNT-YYYY-NNNNNN) and the maintenance audit actions.
--
-- The first part of this file was generated by `prisma migrate diff` from
-- schema.prisma. The hand-written integrity rules follow it: they express
-- what Prisma's schema language cannot, and Prisma ignores them during drift
-- detection.
--
-- Documented in docs/ARCHITECTURE.md sections 3.6 and 4.7.
-- =============================================================================

-- CreateEnum
CREATE TYPE "MaintenanceType" AS ENUM ('PREVENTIVE', 'REPAIR', 'CALIBRATION', 'SOFTWARE_UPDATE', 'WARRANTY_SERVICE', 'OTHER');

-- CreateEnum
CREATE TYPE "MaintenanceStatus" AS ENUM ('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'MAINTENANCE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'MAINTENANCE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'MAINTENANCE_STATUS_CHANGED';

-- AlterEnum
ALTER TYPE "NumberScope" ADD VALUE 'MAINTENANCE';

-- CreateTable
CREATE TABLE "maintenance_records" (
    "id" TEXT NOT NULL,
    "maintenanceNumber" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "issueId" TEXT,
    "type" "MaintenanceType" NOT NULL,
    "status" "MaintenanceStatus" NOT NULL DEFAULT 'SCHEDULED',
    "title" TEXT NOT NULL,
    "description" TEXT,
    "scheduledFor" TIMESTAMPTZ(3),
    "startedAt" TIMESTAMPTZ(3),
    "completedAt" TIMESTAMPTZ(3),
    "vendor" TEXT,
    "vendorReference" TEXT,
    "cost" DECIMAL(12,2),
    "currency" VARCHAR(3) NOT NULL DEFAULT 'AED',
    "outcome" TEXT,
    "performedById" TEXT,
    "cancelledAt" TIMESTAMPTZ(3),
    "cancelReason" TEXT,
    "createdById" TEXT NOT NULL,
    "updatedById" TEXT,
    "deletedAt" TIMESTAMPTZ(3),
    "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "maintenance_records_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "maintenance_records_maintenanceNumber_key" ON "maintenance_records"("maintenanceNumber");

-- CreateIndex
CREATE INDEX "maintenance_records_assetId_status_idx" ON "maintenance_records"("assetId", "status");

-- CreateIndex
CREATE INDEX "maintenance_records_issueId_idx" ON "maintenance_records"("issueId");

-- CreateIndex
CREATE INDEX "maintenance_records_status_scheduledFor_idx" ON "maintenance_records"("status", "scheduledFor");

-- CreateIndex
CREATE INDEX "maintenance_records_performedById_idx" ON "maintenance_records"("performedById");

-- CreateIndex
CREATE INDEX "maintenance_records_deletedAt_idx" ON "maintenance_records"("deletedAt");

-- CreateIndex
CREATE INDEX "maintenance_records_number_trgm" ON "maintenance_records" USING GIN ("maintenanceNumber" gin_trgm_ops);

-- AddForeignKey
ALTER TABLE "maintenance_records" ADD CONSTRAINT "maintenance_records_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "assets"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_records" ADD CONSTRAINT "maintenance_records_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "issues"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_records" ADD CONSTRAINT "maintenance_records_performedById_fkey" FOREIGN KEY ("performedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_records" ADD CONSTRAINT "maintenance_records_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "maintenance_records" ADD CONSTRAINT "maintenance_records_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;


-- =============================================================================
-- Hand-written integrity rules
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Work cannot finish before it starts
-- -----------------------------------------------------------------------------
ALTER TABLE "maintenance_records"
  ADD CONSTRAINT "maintenance_records_completed_after_started"
  CHECK (
    "completedAt" IS NULL
    OR "startedAt" IS NULL
    OR "completedAt" >= "startedAt"
  );

-- -----------------------------------------------------------------------------
-- 2. Status and its timestamps agree
-- -----------------------------------------------------------------------------
-- A record is COMPLETED exactly when completedAt is set, CANCELLED exactly when
-- cancelledAt is set, and cannot be IN_PROGRESS without a start time. This
-- stops a UI bug from producing "completed" work with no completion date - the
-- date is what the annual calibration report is built from.
ALTER TABLE "maintenance_records"
  ADD CONSTRAINT "maintenance_records_status_matches_timestamps"
  CHECK (
    ("status" = 'COMPLETED') = ("completedAt" IS NOT NULL)
    AND ("status" = 'CANCELLED') = ("cancelledAt" IS NOT NULL)
    AND ("status" <> 'IN_PROGRESS' OR "startedAt" IS NOT NULL)
  );

-- -----------------------------------------------------------------------------
-- 3. Money is sane
-- -----------------------------------------------------------------------------
ALTER TABLE "maintenance_records"
  ADD CONSTRAINT "maintenance_records_cost_not_negative"
  CHECK ("cost" IS NULL OR "cost" >= 0);

-- ISO 4217 codes are three upper-case letters. The default is AED; the
-- `maintenance.defaultCurrency` setting pre-fills the UI.
ALTER TABLE "maintenance_records"
  ADD CONSTRAINT "maintenance_records_currency_is_iso4217"
  CHECK ("currency" ~ '^[A-Z]{3}$');

-- -----------------------------------------------------------------------------
-- 4. An asset is in at most one workshop at a time
-- -----------------------------------------------------------------------------
-- Several SCHEDULED records per asset are legitimate (annual calibration plus
-- a planned repair). Only one may be actively underway - IN_PROGRESS, or
-- ON_HOLD while it sits at a vendor waiting for parts.
CREATE UNIQUE INDEX "maintenance_records_one_active_per_asset"
  ON "maintenance_records" ("assetId")
  WHERE "deletedAt" IS NULL
    AND "status" IN ('IN_PROGRESS', 'ON_HOLD');

-- -----------------------------------------------------------------------------
-- 5. Dashboard supporting index
-- -----------------------------------------------------------------------------
-- "Maintenance due" and "overdue maintenance" scan only open records; completed
-- and cancelled history stays out of the way permanently.
CREATE INDEX "maintenance_records_open_by_scheduled_for"
  ON "maintenance_records" ("scheduledFor")
  WHERE "deletedAt" IS NULL
    AND "status" IN ('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD');
